### ISSUE TITLE
First bot connecting as a user and not a bot

### ISSUE THREAD

**Issue by karimcambridge** [samp-incognito/samp-irc-plugin#2] opened 2015-11-03 05:37 UTC
Hello, recently I've been getting the issue where the bot ID 1 out of my 3 bots is connecting and not like being recognized as a bot. She doesn't Identify and other stuff, then she quits due to ping timeout from IRC_OnUserDisconnected instead of IRC_OnDisconnected.

```

[18:56:27] [IRC]: IRC_OnConnect: Bot id: 1 Has Connected To 37.59.63.55: 6667
[18:56:28] [IRC]: IRC_OnConnect: Bot id: 2 Has Connected To 37.59.63.55: 6667
[18:56:30] [IRC]: IRC_OnUserNotice (Bot ID 2): User NickServ (NickServ@services.irc.tl) Sent A Notice To JessicaK: This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>.
[18:56:30] [IRC]: IRC_OnUserNotice (Bot ID 2): User NickServ (NickServ@services.irc.tl) Sent A Notice To JessicaK: You have 30 seconds to identify to your nickname before it is changed.
[18:56:30] [IRC]: IRC_OnUserNotice (Bot ID 2): User NickServ (NickServ@services.irc.tl) Sent A Notice To JessicaK: You are now identified for Jessica.
[18:56:30] [IRC]: IRC_OnJoinChannel: Bot id: 2 Has Joined Channel #lvcnr.echo.
[18:56:30] [IRC]: IRC_OnUserSetChannelMode: User: Santa on #lvcnr.echo Set The Irc Mode To: +v JessicaK!
[18:56:30] [IRC]: IRC_OnConnect: Bot id: 3 Has Connected To 37.59.63.55: 6667

[18:56:31] [IRC]: IRC_OnUserNotice (Bot ID 3): User NickServ (NickServ@services.irc.tl) Sent A Notice To JessicaP: This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>.
[18:56:31] [IRC]: IRC_OnUserNotice (Bot ID 3): User NickServ (NickServ@services.irc.tl) Sent A Notice To JessicaP: You have 30 seconds to identify to your nickname before it is changed.
[18:56:31] [IRC]: IRC_OnUserNotice (Bot ID 2): User NickServ (NickServ@services.irc.tl) Sent A Notice To JessicaK: JessicaP!JessicaP@ip-996ad0b5.kimsufi.com has just authenticated as you (Jessica)
[18:56:31] [IRC]: IRC_OnUserNotice (Bot ID 3): User NickServ (NickServ@services.irc.tl) Sent A Notice To JessicaP: You are now identified for Jessica.
[18:56:31] [IRC]: IRC_OnJoinChannel: Bot id: 3 Has Joined Channel #lvcnr.echo.
[18:56:31] [IRC]: IRC_OnUserJoinChannel Bot id: 2 User JessicaP Has Joined The Channel (#lvcnr.echo)!
[18:56:31] [IRC]: IRC_OnUserJoinChannel Bot id: 2 User JessicaP Has Joined The Channel (#kcnr.adminchat)!
[18:56:31] [IRC]: IRC_OnUserSetChannelMode: User: Santa on #lvcnr.echo Set The Irc Mode To: +v JessicaP!
[18:56:32] [IRC]: IRC_OnUserSetChannelMode: User: Santa on #lvcnr.echo Set The Irc Mode To: +v JessicaP!

[19:56:02] [IRC]: IRC_OnUserDisconnect: bot ID: 3. User: Jessica Has Disconnected! (Ping timeout: 121 seconds)
[19:56:02] [IRC]: IRC_OnUserDisconnect: bot ID: 2. User: Jessica Has Disconnected! (Ping timeout: 121 seconds)
```

At the current moment the first bot (Jessica) connected fine.. the code has not changed

```
[02:21:48] [IRC]: IRC_OnConnect: Bot id: 1 Has Connected To 37.59.63.55: 6667
[02:21:49] [IRC]: IRC_OnUserNotice (Bot ID 1): User NickServ (NickServ@services.irc.tl) Sent A Notice To Jessica: This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>.
[02:21:49] [IRC]: IRC_OnUserNotice (Bot ID 1): User NickServ (NickServ@services.irc.tl) Sent A Notice To Jessica: You have 30 seconds to identify to your nickname before it is changed.
[02:21:49] [IRC]: IRC_OnUserNotice (Bot ID 1): User NickServ (NickServ@services.irc.tl) Sent A Notice To Jessica: You are now identified for Jessica.
[02:21:49] [IRC]: IRC_OnJoinChannel: Bot id: 1 Has Joined Channel #lvcnr.echo.

[02:21:53] [IRC]: IRC_OnUserNotice (Bot ID 1): User NickServ (NickServ@services.irc.tl) Sent A Notice To Jessica: JessicaK!JessicaK@ip-996ad0b5.kimsufi.com has just authenticated as you (Jessica)

[02:21:53] [IRC]: IRC_OnUserNotice (Bot ID 1): User NickServ (NickServ@services.irc.tl) Sent A Notice To Jessica: JessicaP!JessicaP@ip-996ad0b5.kimsufi.com has just authenticated as you (Jessica)
```

And it's been up for 5 hours now, no issues. Compared to the other times where it times out after 1 hour exactly. Also after it does that, the other 2 bots stop receiving commands like !say etc.

I'd like to note that it repeated happens, like 1/4 times bot id 1 'jessica' connects and runs fine. Other than that.. she quits after some time then the other 2 bots stops responding. They only send messages.

**Comment by samp-incognito** [comment] 2015-11-05 05:00
If the bot is timing out and attempting to reconnect, the nickname could just still be in use from the previous session. Check what's happening under `IRC_OnReceiveRaw`.

N.B. If this is the case, I added functionality in one of the newer versions for alternate nicks. Look at the default filterscript under `IRC_OnReceiveNumeric`.

**Comment by karimcambridge** [comment] 2015-11-05 05:25
It's not the case, because some annoying people started to use my bot names on purpose awhile back so i used that to create a automatic nick fixing feature. It ghosts nicks and changes names temporarily if theres a user already connected with the same name.

```
public IRC_OnReceiveNumeric(botid, numeric, message[])
{
    // Check if the numeric is an error defined by RFC 1459/2812
    if (numeric >= 400 && numeric <= 599)
    {
        if (numeric == 433) // const ERR_NICKNAMEINUSE = 433;
        {
            // Check if the nickname is already in use
            new newName[20];
            format(newName, 20, "%s`", gBotNames[botid - 1]);
            IRC_ChangeNick(botid, newName);
            IRC_SayFormatted(botid, "NickServ", "GHOST %s "#IRC_BOT_PASSWORD"", gBotNames[botid - 1]);
        }
        else if(numeric == 477) // You need to be identified to a registered account to join this channel
        {
            ircBotIdentify(botid);
        }
        printf("*** IRC_OnReceiveNumeric (Bot ID %d): %d (%s)", botid, numeric, message);
    }
    return 1;
}

public IRC_OnUserNotice(botid, recipient[], user[], host[], message[]) // replies to identify
{
    if(strfind(host, "No hostname", true) != -1) return 1;
    printf("[IRC]: IRC_OnUserNotice (Bot ID %d): User %s (%s) Sent A Notice To %s: %s", botid, user, host, recipient, message);
    if(strfind(message, "has been ghosted") != -1) {
        new newName[20];
        format(newName, 20, "%s", gBotNames[botid - 1]);
        IRC_ChangeNick(botid, newName);
        ircBotIdentify(botid);
    }
    return 1;
}
```

IRC Raw data might just give me what I need, thanks I'll try that. I'll reply again after, wait for my reply with that data. Thanks

**Comment by samp-incognito** [comment] 2015-11-05 15:47
Maybe the previous connection is freed by the server (due to ping timeout) right before the GHOST command is used? Just a theory. You should probably also add a check to `IRC_OnUserNotice` to change the nick if the GHOST command fails.

**Comment by karimcambridge** [comment] 2015-11-05 16:02
Just a little bit to help me understand more..

Why would I change the nick if the ghost command fails though? It already changes the nick name to the alternate name if the current nick name is already taken. So your saying if the ghost fails then maybe the connection got free'd before that. 

If its that then I get that, but that will only work out if the bot quits like instantly on connect because thats when the nick in use numeric would be received. This issue happens after either 2 minutes or 1 hour. NOt sure if random or what.

**Comment by samp-incognito** [comment] 2015-11-05 17:25
Are you changing it to an alternate nick, though? You're using `gBotNames[botid - 1]` for both `IRC_ChangeNick` and `IRC_SayFormatted`.

**Comment by karimcambridge** [comment] 2015-11-05 17:37
Sorry, lacked a little info there.

```
new gBotNames[MAX_IRC_BOTS][9] =
{
    {"Jessica"},
    {"JessicaK"},
    {"JessicaP"}//,
    //{"JessicaM"}//,
    //{"JessicaB"}
};
```

Yea, "format(newName, 20, "%s`", gBotNames[botid - 1]);"

The ` for alternate.

**Comment by samp-incognito** [comment] 2015-11-05 18:45
Okay, didn't catch the `. That should work then, though if the GHOST command fails for whatever reason, the nick just won't be changed back. That doesn't appear to be what's happening here, however. I would look at the raw messages to see what you might be missing.

Edit: I didn't see until now that the bot connected with the correct name and just stopped responding. That's odd. Does the problem resolve itself when the bot reconnects? Still, I'd look at the raw messages. It might give you some clue.

**Comment by karimcambridge** [comment] 2015-11-05 19:30
Doesn't matter if the nick isn't changed back, because I have 1 main bot.. 'Jessica'. She is the only registered bot. The other bots use /ns identify Jessica passwordhere. So if ANY bot goes to there alternative nick, even Jessica. They will identify as jessica and get voiced in my channels. Reconnecting doesn't help SOMETIMES. None respond once the main bot, Jessica quits on her own. I'm waiting for the server to crash so get the logs. I don't wanna force a restart just for that atm.

**Comment by karimcambridge** [comment] 2015-11-09 03:10
Okay so this one is weird. Also I've noticed Jessica is quitting due to operation canceled lately. Any idea what is that?

SERVER LOG:

```
[16:48:16] [IRC]: IRC_OnConnect: Bot id: 1 Has Connected To 37.59.63.55: 6667
//-- no accepted no other commands, it didn't even try to identify
[17:31:28] [IRC]: IRC_OnUserDisconnect: bot ID: 2. User: Jessica Has Disconnected! (Ping timeout: 121 seconds)
[17:31:28] [IRC]: IRC_OnUserDisconnect: bot ID: 3. User: Jessica Has Disconnected! (Ping timeout: 121 seconds)
[17:31:28] [IRC]: IRC_OnDisconnect: Bot id: 1 Has Disconnected From 37.59.63.55:6667 (Operation canceled)
```

IRC Raw LOG:

```
//bot connected successfully
[8/11/2015 (16:38:15): 8 LOG] - :exnet.fr.irc.tl NOTICE Auth :*** Looking up your hostname...
[8/11/2015 (16:38:15): 8 LOG] - :exnet.fr.irc.tl NOTICE Auth :*** Found your hostname (ks3357010.kimsufi.com) -- cached
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl NOTICE Auth :Welcome to irc.tl!
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 001 Jessica :Welcome to the irc.tl IRC Network Jessica!Jessica@ks3357010.kimsufi.com
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 002 Jessica :Your host is exnet.fr.irc.tl, running version InspIRCd-2.0
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 003 Jessica :This server was created 10:03:55 Nov 11 2014
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 004 Jessica exnet.fr.irc.tl InspIRCd-2.0 BGHIRSWacdhikorswx ABCFGIJKLMNOPQRSTYabcdefghijklmnopqrstuvz FIJLYabdefghjkloqv
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 005 Jessica AWAYLEN=200 CASEMAPPING=rfc1459 CHANMODES=Ibeg,k,FJLdfjl,ABCGKMNOPQRSTcimnprstuz CHANNELLEN=64 CHANTYPES=# CHARSET=ascii ELIST=MU ESILENCE EXCEPTS=e EXTBAN=,ABCNOQRSTUcjmprz FNC INVEX=I KICKLEN=255 :are supported by this server
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 005 Jessica MAP MAXBANS=60 MAXCHANNELS=20 MAXPARA=32 MAXTARGETS=20 MODES=20 NAMESX NETWORK=irc.tl NICKLEN=31 OPERLOG OVERRIDE PREFIX=(Yqaohv)!~&@+ SILENCE=32 :are supported by this server
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 005 Jessica SSL=[::]:6697 STARTTLS STATUSMSG=!~&@+ TOPICLEN=307 UHNAMES USERIP VBANLIST WALLCHOPS WALLVOICES WATCH=32 :are supported by this server
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 042 Jessica 902ARDGMH :your unique ID
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 375 Jessica :exnet.fr.irc.tl message of the day
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|================================================================|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=========                                              =========|=:exnet.fr.irc.tl 372 Jessica
[8/11/2015 (16:38:16): 8 LOG] -  :-  =|======                 exnet.fr.irc.tl                    ======|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=====           __  ____   ___    ____  __                 =====|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|====           (  )(  _ \ / __)  (_  _)(  )                 ====|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|===             )(  )   /( (__  _  )(  / (_/\                ===|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|====           (__)(__\_) \___)(_)(__) \____/               ====|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|====                                                       =====|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|======                   Provided by                      ======|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|========                  Exnet inc                     ========|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|==========              www.exnet.se                  ==========|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|================================================================|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|====                                                        ====|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                   ------- About --------                     =|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |         Available ports: 6666-6669. Port 6697 for SSL.         |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|==== ------------------- Network Staff -------------------- ====|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                        Administrators:                         |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                   --------------------------                   |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                    Garteus (exnet.*.irc.tl)                    |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                      Mow (foco.*.irc.tl)                       |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                           Operators:                           |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                   --------------------------                   |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                             Aero                               |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                            cessil                              |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                           depleted                             |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                             dugi                               |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                              Ez                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                             Popz                               |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                           Potassium                            |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                          Renegade334                           |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|==== ---------------- Connection Information -------------- ====|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   | Server              Location                    Hosted by      |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   | foco.ca.irc.tl      Montreal, Canada            FoCo Ltd.      |:exnet.fr.irc.tl 372 Jessi
[8/11/2015 (16:38:16): 8 LOG] - ca :-   | exnet.ca.irc.tl     Montreal, Canada            Exnet inc.     |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   | exnet.nl.irc.tl     Amsterdam, The Netherlands  Exnet inc.     |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   | exnet.fr.irc.tl     Roubaix, France             Exnet inc.     |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   | exnet.us.irc.tl     Los Angeles, United States  Exnet inc.     |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|==== --------------------- Disclaimer --------------------- ====|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   | ~  By connecting to this network, you give us permission       |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |    to scan your machine for open proxies.                      |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   | ~  Being on this IRC network is a privilege, not a right.      |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |    Staff members from any of our linked servers                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |    may deny you access to this network for any reason.         |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   | ~  All users must follow international law,                    |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |    and the laws of their country.                              |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:16): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|==== ------------------- Network Rules -------------------- ====|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |             The following is prohibited at this network:       |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |     * Racism and or Nazism.                                    |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |     * Discussing or spreading illegal copyrighted material.    |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |     * Discussing or spreading pornographic material.           |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |     * Spamming and or advertising.                             |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |     * Hacking and or cracking.                                 |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |     * Evading Network and or channel bans.                     |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |     * Flooding.                                                |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |     * Botnets.                                                 |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |             Violation of any rule mentioned above              |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |           might get you banned without prior notice.           |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                       www.irc.tl/rules                         |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |:exnet.fr.irc.tl 372 Jessica :-  =|=
[8/11/2015 (16:38:17): 8 LOG] -                                                               =|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|==== --------------------- Channels ----------------------- ====|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   | #help - Network help channel.                                  |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   | #operhelp - For issues that requires an IRCOp.                 |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   | #foco - General chat channel for FoCo Gaming.                  |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|==== ------------------------ Misc ------------------------ ====|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |          --------------- MOTD STATUS ---------------           |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |          |     Last updated on: 23 Mar 2015        |           |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |          |          Updated by: Garteus            |           |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |          |              Reason: General update     |           |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |          -------------------------------------------           |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-   |                                                                |
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=                                                              =|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|================================================================|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|==========                                            ==========|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|=============              www.irc.tl              =============|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|==============                                    ==============|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|================                                ================|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 372 Jessica :-  =|================================================================|=
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 376 Jessica :End of message of the day.
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 251 Jessica :There are 80 users and 708 invisible on 6 servers
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 252 Jessica 9 :operator(s) online
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 253 Jessica 100 :unknown connections
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 254 Jessica 915 :channels formed
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 255 Jessica :I have 370 clients and 1 servers
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 265 Jessica :Current Local Users: 370  Max: 532:exnet.fr.irc.tl 266 Jessica :Current Global 
[8/11/2015 (16:38:17): 8 LOG] - Users: 788  Max: 877
[8/11/2015 (16:38:17): 8 LOG] - :exnet.fr.irc.tl 396 Jessica ip-996ad0b5.kimsufi.com :is now your displayed host
[8/11/2015 (16:38:17): 8 LOG] - :Jessica!Jessica@ip-996ad0b5.kimsufi.com MODE Jessica +iwx
```

Hmm.. bot didn't seem to try to identify. Server crashed here.. you said something about bot ids in the plugin here right?

Because my used to identify is 

```
ircBotIdentify(botid)
{
    if(botid > 1)
        IRC_SayFormatted(botid, "NickServ", "IDENTIFY %s "#IRC_BOT_PASSWORD"", gBotNames[0]);
    else
        IRC_Say(botid, "NickServ", "IDENTIFY "#IRC_BOT_PASSWORD"");
}
```

but it didn't even attempt an identify, even through both of those should work with the 'Jessica' bot because she's the group owner.

The other bots identified as her fine, she's on all channel user lists.

Weirdly enough, she starts sending messages then she somehow quits.

```
[8/11/2015 (17:31:28): 8 LOG] - :Jessica!Jessica@ip-996ad0b5.kimsufi.com QUIT :Ping timeout: 121 seconds
[8/11/2015 (17:31:28): 8 LOG] - :Jessica!Jessica@ip-996ad0b5.kimsufi.com QUIT :Ping timeout: 121 seconds
```

**Comment by samp-incognito** [comment] 2016-01-02 21:34
See if v1.4.7 fixes it. If it doesn't, I'm not really sure since I can't reproduce it. It looks like it could be a problem with Boost.Asio, which could be fixed by compiling with a newer version of the library than the one supplied in this repository. I don't have much time at all to devote to this anymore, unfortunately.

**Closed as completed by samp-incognito** 2016-01-02 21:34 UTC

**Comment by karimcambridge** [comment] 2016-05-17 20:21
Ubuntu Trusty Tahr fixed it.

Must've been a boost issue.
